from __future__ import annotations

WARN_NULL_UNIFY = "warn_null_unify"
WARN_AMBIGUOUS = "warn_ambiguous"
WARN_HIGH_NULL = "warn_high_null"
WARN_DUPLICATE_COLUMNS = "warn_duplicate_columns"
WARN_FUTURE_DATES = "warn_future_dates"
WARN_EMAIL_SHAPE = "warn_email_shape"
WARN_NEGATIVE_VALUES = "warn_negative_values"
WARN_CONFLICT = "warn_conflict"
WARN_DATE_UNPARSED = "warn_date_unparsed"
WARN_DATE_AMBIGUOUS = "warn_date_ambiguous"
WARN_DATE_NONE = "warn_date_none"
WARN_CAT_MERGED = "warn_cat_merged"
WARN_DUP_UNKNOWN = "warn_dup_unknown"
WARN_DUP_TRUNCATED = "warn_dup_truncated"
WARN_DUP_GROUPS = "warn_dup_groups"
